### ISSUE TITLE
Not working with wow8.1/Kui Nameplates 2.18.2

### ISSUE THREAD

**Issue by Kedik** [kesava-wow/kuinameplates-customs#15]
The customs file does not affect the nameplates since the latest update for kui nameplates

**Comment by Aur0r4** [comment]
I can confirm this. Got this error:

2x Kui_Nameplates\messages.lua:540: Out of date plugin `OldTextures` ignored
[C]: in function `error'
Kui_Nameplates\messages.lua:540: in function `NewPlugin'
Kui_Nameplates_OldTextures\custom-Benutzer.lua:4: in main chunk

Locals:
(*temporary) = "Out of date plugin `OldTextures` ignored"

**Comment by Kedik** [comment]
Actually i was talking about Kui_Nameplates_Customs not taking in the customisation like show % or other colorbar depending on enemy name. I was trying to use Kui_Nameplates_OldTextures thinking this is to replace Customs but I could not figure out what OldTextures is for

**Comment by kesava-wow** [comment]
There should be an error in game telling you which script is out of date. Redownload it from the repository, following the same steps as when you first installed it, in the readme. Two scripts haven't been updated yet because they rely on something which was removed in 2.18.2, so it's more complex to fix them.
